### PR TITLE
Fixing the issue of the assembly is being stripped on mobile leading to broken events

### PR DESCRIPTION
**Pull request by AhmadMansy**
## Changes

> Fixing broken events on mobile when the stripping code level is set to 'low' or above
> Upgrading to Unity 2022.3 LTS
> Fixing compiler errors due to Newtonfost package not added to the project

### CODE REVIEW

**Comment by j1mmie** [comment]
I was also running into the issue of broken events. The JSON generated for my events was being truncated. I added the link.xml to my own project and that fixes it.

I definitely think this PR should be merged. Any chance of that happening?

**Comment by desusai7** [comment]
Hello @j1mmie, 

We are actively looking into this, will keep you posted.

**Comment by desusai7** [comment]
Hello @j1mmie, 

We are actively looking into this, will keep you posted.

**Comment by ChryssaAliferi** [comment]
> ## Changes
> > Fixing broken events on mobile when the stripping code level is set to 'low' or above
> > Upgrading to Unity 2022.3 LTS
> > Fixing compiler errors due to Newtonfost package not added to the project

Hello @AhmadMansy and sorry it took us so long to get back to you.
Thank you very much for contributing to this PR. I do believe as well that this PR needs to be merged. After a careful look and testing I am approving this PR.
Could you please kindly [sign the Contributor License Agreement (CLA)](https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement) before merging?

Thank you again!

**Review by ChryssaAliferi — APPROVED** [review]

**Comment by AhmadMansy** [comment]
@ChryssaAliferi Thank you.
And I signed the agreement

**Pull request merged**
